# -*- coding: utf-8 -*-
"""audio_scripts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgOHByeXVGWepyZhs0_atUmiIj_4CoFj
"""

!pip install -q librosa soundfile
import os
import numpy as np
import pandas as pd
import librosa
import librosa.display
import matplotlib.pyplot as plt
import IPython.display as ipd

from google.colab import files
uploaded = files.upload()   # select everyone's .wav files
print("Uploaded:", list(uploaded.keys()))

import os

# --- Cell 3: build the audio catalog by checking the local disk ---
members = ["dan", "enock", "hugues", "urlich"]
phrases = ["yes_approve", "confirm_transaction"]
SR = 22050

audio_catalog = {}
# List all files in the current directory
current_files = os.listdir('.')

for fname in current_files:
    for m in members:
        for p in phrases:
            # Check if both member name and phrase are in the filename
            if m in fname.lower() and p in fname.lower():
                audio_catalog[fname] = (m, p)

print(f"{len(audio_catalog)} clips found on disk:")
for fname, (member_id, phrase) in audio_catalog.items():
    print(f"   {fname:<40} -> member={member_id}, phrase={phrase}")

clips = {}
for fname, (member_id, phrase) in audio_catalog.items():
    if not os.path.exists(fname):
        print("WARNING - not found, skipping:", fname)
        continue
    # librosa can handle .ogg, .mpeg, .mp4 if ffmpeg is present (default in Colab)
    y, sr = librosa.load(fname, sr=SR)
    clips[fname] = y
    print(f"Loaded {fname}: {len(y)/sr:.2f}s")

for fname, y in clips.items():
    member_id, phrase = audio_catalog[fname]
    fig, ax = plt.subplots(1, 2, figsize=(14, 3))

    librosa.display.waveshow(y, sr=SR, ax=ax[0])
    ax[0].set_title(f"{member_id} — {phrase} — waveform")

    D = librosa.amplitude_to_db(np.abs(librosa.stft(y)), ref=np.max)
    img = librosa.display.specshow(D, sr=SR, x_axis="time", y_axis="hz", ax=ax[1])
    ax[1].set_title(f"{member_id} — {phrase} — spectrogram")
    fig.colorbar(img, ax=ax[1], format="%+2.0f dB")

    plt.tight_layout(); plt.show()
    display(ipd.Audio(y, rate=SR))   # lets you actually hear it

def augment(y, sr=SR):
    noise = y + 0.005 * np.random.randn(len(y))
    return {
        "original":     y,
        "pitch_shift":  librosa.effects.pitch_shift(y, sr=sr, n_steps=2),
        "time_stretch": librosa.effects.time_stretch(y, rate=1.15),
        "noise":        noise.astype(np.float32),
    }

def extract_features(y, sr=SR):
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13).mean(axis=1)   # 13 values
    rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr).mean()      # 1 value
    energy = float(np.sqrt(np.mean(y**2)))                             # RMS, 1 value
    return mfcc, float(rolloff), energy

rows = []
for fname, (member_id, phrase) in audio_catalog.items():
    if fname not in clips:
        continue
    for aug_name, y_aug in augment(clips[fname]).items():
        mfcc, rolloff, energy = extract_features(y_aug)
        row = {
            "member_id":    member_id,
            "clip_id":      f"{fname.rsplit('.', 1)[0]}_{aug_name}",
            "phrase":       phrase,
            "augmentation": aug_name,
            "label":        member_id,
        }
        for i, v in enumerate(mfcc):
            row[f"mfcc_{i}"] = v
        row["spectral_rolloff"] = rolloff
        row["energy"] = energy
        rows.append(row)

df_audio = pd.DataFrame(rows)
df_audio.to_csv("audio_features.csv", index=False)
print("Shape:", df_audio.shape)
print(df_audio["member_id"].value_counts())
df_audio.head()

feat_cols = [c for c in df_audio.columns if c.startswith(("mfcc_", "spectral_", "energy"))]
print("Duplicate feature rows:", df_audio.duplicated(subset=feat_cols).sum())

files.download("audio_features.csv")